[package]
name = "chess-alpha-beta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap  = { version = "4.5.4", features = ["derive"] }
pleco = "0.5.0"
rand = "0.8.5"
rayon = "1.10.0"
regex = "1.10.4"
