[package]
name = "chess-alpha-beta"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pleco = "0.5.0"
rand = "0.7.3"
clap = "2.33.1"
regex = "1.3.9"
