name: Build and deploy app

on:
  push:
    branches:
      - master

jobs:
  build_front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build
        working-directory: front
        run: |
          npm ci
          npm run build

      - name: Create artifacts
        uses: actions/upload-artifact@v4
        with:
          name: front
          path: front/dist

  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Build rust exe
        run: |
          cargo fetch --locked
          cargo build --frozen --release

      - name: Create artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: target/release/chess-alpha-beta-server

  deploy:
    needs: [build_front, build_backend]
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH client
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          cat << EOF > ~/.ssh/config
            Host prod
            HostName ${{secrets.DEPLOY_HOST}}
            Port ${{secrets.SSH_PORT}}
            User github-runner-chess
            StrictHostKeyChecking no
          EOF

      - name: Download front artifacts
        uses: actions/download-artifact@v4
        with:
          name: front
          path: front

      - name: Download server artifacts
        uses: actions/download-artifact@v4
        with:
          name: server
          path: server

      - name: Upload artifacts to prod
        run: |
          rsync --archive --delete --verbose front/ prod:/var/www/chess
          rsync --archive --delete --verbose server/ prod:/opt/chess

      - name: Restart service
        run: ssh prod sudo systemctl restart chess-alpha-beta.service
